AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'orders-processor Sample SAM Template for orders-processor

  '
Globals:
  Function:
    Timeout: 3
Resources:
  OrdersStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: OrdersStream
      ShardCount: 1
  OrdersDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Jobs
      AttributeDefinitions:
      - AttributeName: CustomerID
        AttributeType: S
      - AttributeName: OrderID
        AttributeType: S
      KeySchema:
      - AttributeName: CustomerID
        KeyType: HASH
      - AttributeName: OrderID
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  OrdersProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrdersProcessingFunction
      CodeUri: s3://dakobed-serverless-apis/34ece264da1b662ab6432ff5885acdfc
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
